Update project-setup.yml

diff --git a/.github/workflows/project-setup.yml b/.github/workflows/project-setup.yml
--- a/.github/workflows/project-setup.yml
+++ b/.github/workflows/project-setup.yml
@@ -85,21 +85,21 @@ jobs:
         env:
           REPO_NAME: ${{ github.repository }}
         run: |
-          if [ -f "sonar-projects.properties" ]; then
-            sed -i "s/{{repo_name}}/${REPO_NAME##*/}/g" sonar-projects.properties
-            echo "sonar-projects.properties file found. Updating."
+          if [ -f "sonar-project.properties" ]; then
+            sed -i "s/{{repo_name}}/${REPO_NAME##*/}/g" sonar-project.properties
+            echo "sonar-project.properties file found. Updating."
           else
-            echo "sonar-projects.properties file not found. Skipping."
+            echo "sonar-project.properties file not found. Skipping."
           fi
       - name: Create flag file to mark initialization
         run: |
           mkdir -p .github
-          echo "Initialized sonar-projects.properties" > .github/.sonar-projects.properties-initialized
+          echo "Initialized sonar-project.properties" > .github/.sonar-project.properties-initialized
       - name: Commit changes
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           git config --global user.name "github-actions"
-          git add sonar-projects.properties .github/.sonar-projects.properties-initialized
-          git commit -m "Initialize sonar-projects.properties with repo name" || echo "No changes to commit."
+          git add sonar-project.properties .github/.sonar-project.properties-initialized
+          git commit -m "Initialize sonar-project.properties with repo name" || echo "No changes to commit."
           git push origin $(git rev-parse --abbrev-ref HEAD)
